name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lua 5.4
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4

    - name: Run tests
      run: |
        lua test.lua
